pipeline {
    agent any
    tools {
        // Define the Maven installation from Jenkins configuration
        maven 'Maven'
    }
    stages {
        stage('Checkout') {
            steps {
                // Checkout the source code from your SCM
                checkout scm
            }
        }
        
        stage('Build') {
            steps {
                // Build the Maven project using Windows batch command                
                dir('payroll') {
                    bat 'mvn clean package'
                }

            }
        }
        
        stage('Test') {
            steps {
                // Run tests (if any) using Windows batch command
                dir('payroll') {
                    bat 'mvn test'
                }
            }
        }

        stage('Deploy to Tomcat') {
            steps {
                dir('payroll') {
                    bat 'copy target\\*.war F:\\Takneekigyanguru\\Installation\\Software\\Tomcat\\apache-tomcat-10.1.23-windows-x64\\apache-tomcat-10.1.23\\webapps'
                }
            }
        }
    }
}